### ISSUE TITLE
how to use the enchantment?

### ISSUE THREAD

**Issue by harankr8** [mastery3/unbreakable#2]
i couldent find anything regarding how to use the enchantment?

**Comment by mastery3** [comment]
With commands: `/enchant @s mastery3:unbreakable`

In a Survival world, you can obtain it as you would other treasure enchantments.

The enchantment makes your item unbreakable (it functions similar to Unbreaking, except that the item has a 100% chance of not taking damage.)

**Comment by harankr8** [comment]
thx
