### ISSUE TITLE
book

### ISSUE THREAD

**Issue by itzsweats** [mastery3/unbreakable#3]
how do i get the actual book in survival, like what structure would most likely have it?

**Comment by mastery3** [comment]
There's no specific structure that Indestructible books are more likely to generate in; the only difference is that these books are rarer than most treasure enchantments.

Treasure enchantments are typically found by trading with villagers, fishing, and looting end cities. Basically, the same advice for vanilla Mending also applies to the Indestructible enchantment from this mod.

**Comment by itzsweats** [comment]
IM CONVINCED THIS IS IMPOSSIBLE, ive looted 13 ancient cities, and have rerolled a villager for the past 3 hours and i have yet to get the book, am i just this unlucky..

**Comment by mastery3** [comment]
That might indicate a bug (introduced by the 1.21 update?); I'll check it out later.

**Comment by mastery3** [comment]
After investigating, it appears that it is indeed impossible to get the book (for an unknown reason). I'll fix it tomorrow.

**Comment by mastery3** [comment]
Fixed
