### ISSUE TITLE
Can't seem to get the enchanted book

### ISSUE THREAD

**Issue by Professor-Puddle** [mastery3/unbreakable#4]
I've installed the mod on a 1.21 server and my client, and I've been trying for over an hour to get the book on my server from librarians, but I still haven't gotten it. 

Am I doing something wrong? Or is the enchant not in the librarian's enchant list thing?

**Comment by mastery3** [comment]
Not in the librarian's enchantment list. Seems to be another instance of #3. In the meantime, get your books from a different source.

**Comment by Professor-Puddle** [comment]
I see. Thanks for the reply. Hope this gets fixed soon.

(The end is locked till the 15th august soo I guess we'll just stick to ancient city looting lol)

**Comment by mastery3** [comment]
Fixed in latest update
